### ISSUE TITLE
How Can I run this code in CPU only mode?

### ISSUE THREAD

**Issue by bemoregt** [szagoruyko/diracnets#10]
HI, @soumith @szagoruyko.

How Can I run this code in CPU only mode?

Is that Possible ?

Thanks.

**Comment by szagoruyko** [comment]
fixed it, you can check by adding `--ngpu ''` flags

**Comment by bemoregt** [comment]
Him @szagoruyko @soumith 

I fixed it by not --ngpu '' but --ngpu 0.

Thanks.
