### ISSUE TITLE
invalid combination of arguments when run the tran.py

### ISSUE THREAD

**Issue by chituma110** [szagoruyko/diracnets#18]
raceback (most recent call last):
  File "train.py", line 230, in <module>
    main()
  File "train.py", line 118, in main
    f, params, stats = define_diracnet(opt.depth, opt.width, opt.dataset)
  File "/home/amax/cqs/diracnets/diracnet.py", line 126, in define_diracnet
    'conv': cast(kaiming_normal(torch.Tensor(widths[0], 3, 3, 3))),
TypeError: new() received an invalid combination of arguments - got (Tensor, int, int, int), but expected one of:
 * (torch.device device)
 * (tuple of ints size, torch.device device)
 * (torch.Storage storage)
 * (Tensor other)
 * (object data, torch.device device)

**Comment by FzuLJ** [comment]
Change your pytorch version.
I got the same problem when I use pytorch 0.4.0.  Then I try to get the pytorch back to 0.2.0 and solved this problem.

**Comment by chituma110** [comment]
@FzuLJ thank you for your reply. I have solved the problem.
